### ISSUE TITLE
CI/CD is broken

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/factory#10]
Travis builds are broken, see the latest build - https://travis-ci.org/datopian/factory/builds/549083095

The problem appeared when the repository was transferred from `datahq` org to `datopian`. All the settings were lost during the transfer which were required for Travis builds.

I've looked at logs in Travis:

* it fails to decrypt the file with credentials - https://travis-ci.org/datopian/factory/builds/549083095#L698-L700
  * this happens because `encrypted_f31baa052f19_key` and `encrypted_f31baa052f19_iv` env vars are missing
* as a result subsequent command fails as well - https://travis-ci.org/datopian/factory/builds/549083095#L702-L705
* which then causes the build fail - https://travis-ci.org/datopian/factory/builds/549083095#L752-L755

## Acceptance criteria

* [ ] Travis succeeds
* [ ] Travis opens a PR in deploy repo

## Tasks

* [ ] fix decryption of secrets
  * [ ] find out what exactly is in `secrets.tar.enc`
  * [ ] create a new `secrets` file with similar content
  * [ ] encrypt it using travis ci and set up travis so it knows how to decrypt (there should be docs in travis about that)
  * [ ] push encrypted file
* [ ] fix deployment
  * [ ] setup env vars in Travis: `DOCKER_PASSWORD`, `DOCKER_USERNAME`, `GITHUB_TOKEN`

**Comment by anuveyatsu** [comment]
@zelima please note this is **not** urgent.

We probably will need to understand where we can get `DOCKER_PASSWORD`, `DOCKER_USERNAME` and `GITHUB_TOKEN`:

* Which account are we using for docker?
* As I can see we're using `datopianbot` user in github so `GITHUB_TOKEN` should be easy to get for us.

We also need to know how decrypted `secrets` file looks like. My guess is that it is a standard JSON config file for `core` user:

```json
{
  "token": "...",
  "api": "...",
  "profile": {
    "avatar_url": "...",
    "email": "...",
    "id": "...",
    "join_date": "...",
    "name": "...",
    "provider_id": "...",
    "username": "..."
  }
}
```

**Comment by zelima** [comment]
@anuveyatsu 
- As much as I remember those were my personal credentials for docker - so you could either use yours or create a new user for that purpose (if there is not one already)
- Yes re Github token - just create new one
- Yes re decrypted `secrets`. It was config.json file for datahub (for core user)

**Comment by svetozarstojkovic** [comment]
After one hour of an investigation of this problem by @zelima and I, we found out that the problem is bigger than expected.

For some reason we have:
* https://travis-ci.com/datopian/factory
* https://travis-ci.org/datopian/factory

In Travis documentation it is said that in the future we should only use travis-ci.com not travis-ci.org [source](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps#heres-how-to-jump-in).

Also in last couple of days pipeline repo completely crashed: https://api.datahub.io/factory/

To solve this problem we need access to deploy of this factory repo on Kubernetes to see the logs why it cannot be deployed with updated code.
