### ISSUE TITLE
Handle multiple config files

### ISSUE THREAD

**Issue by zelima** [datahq/factory#2]
As a publisher, I want to be able to run factory under multiple different accounts so that I can publish and automate them under users o my choice, or allow somebody else to publish datasets in an automated way

## Acceptance Criteria

* [x] datasets are published and scheduled under datahq  user as well (Eg KPIs)

## Tasks

* [x] Do an analysis
  * [x] Think about structure 
  * [x] Think About naming
  * [x] Think about how it may be easily updated
* [x] Come up woth solution and refactor
* [x] Update README
* [x] Translate footbal script into dataflows https://github.com/datasets/football-datasets/issues/1

### Structure

datasets will be placed in the directories named under the publisher name. and each user will have it's own encripted `config.json.enc` file. Eg

```
├── datasets
│   ├── core
│   │   ├── airport-codes
│   │   ├── bond-yields-uk-10y
│   │   ├── bond-yields-us-10y
│   │   ├── population-growth-estimates-and-projections
│   │   ├── exchange-rates
│   │   ├── finance-vix
│   │   ├── gold-prices
│   │   ├── household-income-us-historical
│   │   ├── natural-gas-prices
│   │   ├── oil-prices
│   │   └── config.json.enc
│   └── datahq
│       ├── datahub-kpis
│       └── config.json.enc
```

### Naming and using of config files

Unfortunately at the moment data-cli is not accepting custom config file name as an option. But we can modify default config path by exporting the DATAHUB_JSON env variable. So config files will be coppied with stucture and naming:

```
~/.config/datahub/config.json.[username]

Eg: 
~/.config/datahub/config.json.core
~/.config/datahub/config.json.datahq
```

Default config file (`~/.config/datahub/config.json`) will point to the configs of core.

The process above will be automated.

### Updating

According to above we need to do folowing to add/update config

* Encript file and place in `datasets/[username]` directory
* update travis to decript file befor edeploy
* Update `pipeline.yaml` for each dataset and define path to config file Eg 

```
finance-vix-flow:
  pipeline:
    - flow: finance_vix_flow
    - run: datahub.dump.to_datahub
      parameters: 
         config: ~/.config/datahub/config.json.core
  schedule:
    crontab: 59 23 * * *
```

**Comment by zelima** [comment]
FIXED
