### ISSUE TITLE
Travis can not decrypt multiple files  

### ISSUE THREAD

**Issue by zelima** [datahq/factory#3]
As said in their docs if we want to decrypt multiple config files we need to archive them and encrypt a single file. Meaning we have to change approach for saving secrets.

## Acceptance Criteria

* [x] We are able to use decrypt config files
* [x] Desirably easily shareable 

## Tasks

* [x] refactor scryps
* [x] Rewrite README
* [x] update travis
* [x] save encrypted archive in Gitlab

**Comment by zelima** [comment]
FIXED
